# Copyright (c) 2024-2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# UWSGI_CHEAPER sets the number of initial uWSGI worker processes
# UWSGI_PROCESSES sets the maximum number of uWSGI worker processes
ARG UWSGI_CHEAPER=5
ARG UWSGI_PROCESSES=10

# Use the base image with Python 3.13
FROM public.ecr.aws/docker/library/python:3.13-slim-bookworm

# Install dependencies
RUN apt update && \
    apt upgrade && \
    apt install -y --no-install-recommends libexpat1 && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Create a non-root user
ARG UID=1000
ARG GID=1000
# Handle case where GID already exists (e.g. dialout on macOS) or UID exists (e.g. root)
RUN groupadd -g "${GID}" sandboxgroup || true && \
    useradd -u "${UID}" -g "${GID}" -o -m -s /bin/bash sandboxuser

# Set up application code and install Python dependencies
COPY sandbox.requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY local_sandbox_server.py /app/main.py

# Create workspace and set permissions
# Use GID instead of group name in case groupadd failed due to existing GID
RUN mkdir -p /workspace && \
    chown -R sandboxuser:"${GID}" /app /workspace

# Set Flask app environment variables and ports
ARG UWSGI_CHEAPER
ENV UWSGI_CHEAPER=$UWSGI_CHEAPER

ARG UWSGI_PROCESSES
ENV UWSGI_PROCESSES=$UWSGI_PROCESSES

ENV LISTEN_PORT=6000
EXPOSE 6000

# Switch to non-root user
USER sandboxuser

WORKDIR /app
CMD uwsgi --http 0.0.0.0:${LISTEN_PORT} --master -p ${UWSGI_PROCESSES} --force-cwd /workspace -w main:app
